"""Ensure that we can load a model"""
import astropy.units as uu
import inspect
import numpy as np
import types
import unittest

from redback.transient_models.learned_models import make_learned_model_callable

class _DummyModel:
    """A dummy model class for testing purposes that generates a 
    Gaussian-modulated sine wave from the parameters = (freq, amp,
    center, and width) in erg/s/Hz.
    """
    def __init__(self):
        self.param_names = ["freq", "amp", "center", "width"]
        self.times = np.arange(-10, 50, 1)
        self.wavelengths = np.arange(1000, 10000, 200)

    def predict_spectra_grid(self, freq=1.0, amp=1.0, center=5000.0, width=100.0):
        """A dummy predict method that returns a grid based on input parameters."""
        gaussian_envelope = np.exp(-((self.wavelengths - center) ** 2) / (2 * width**2))
        sine_wave = amp * np.sin(2 * np.pi * freq * self.times)
        return (gaussian_envelope[None, :] * sine_wave[:, None]) * uu.erg / uu.s / uu.Hz


class TestLearnedModels(unittest.TestCase):

    def test_make_learned_model_callable(self):
        """Test the tophat_redback model against reference data.
        
        If this test fails the reference data can be regenerated by running
        the make_afterglow_ref_data.py script in the reference_results directory.
        """
        model = _DummyModel()
        func = make_learned_model_callable(model)

        spectra1 = func(
            time=model.times,
            freq=1.0,
            amp=1.0,
            center=5000.0,
            width=100.0,
            output_format="flux_density",
            frequency=3000.0,
        )
        assert spectra1.shape == (len(model.times),)

        spectra2 = func(
            time=model.times,
            freq=2.0,
            amp=5.0,
            center=6000.0,
            width=200.0,
            output_format="flux_density",
            frequency=3000.0,
        )
        assert spectra2.shape == (len(model.times),)

        # Spectra generated with different parameters should not be the same.
        assert not np.allclose(spectra1, spectra2)