"""Ensure that we can load a model"""
import astropy.units as uu
import inspect
import numpy as np
import types
import unittest

from redback.transient_models.learned_models import make_learned_model_callable

class _DummyModel:
    """A dummy model class for testing purposes that generates a 
    Gaussian-modulated sine wave from the parameters = (freq, amp,
    center, and width) in erg/s/Hz.
    """
    def __init__(self):
        self.param_names = ["freq", "amp", "center", "width"]
        self.times = np.arange(-10, 50, 1)
        self.wavelengths = np.arange(1000, 10000, 200)

    def predict_spectra_grid(self, freq=1.0, amp=1.0, center=5000.0, width=1000.0):
        """A dummy predict method that returns a grid based on input parameters."""
        gaussian_envelope = np.exp(-((self.wavelengths - center) ** 2) / (2 * width**2))
        sine_wave = amp * (1.0 + np.sin(2 * np.pi * freq * self.times))
        return (gaussian_envelope[None, :] * sine_wave[:, None]) * uu.erg / uu.s / uu.Hz


class TestLearnedModels(unittest.TestCase):

    def test_make_learned_model_callable(self):
        """Test the tophat_redback model against reference data.
        
        If this test fails the reference data can be regenerated by running
        the make_afterglow_ref_data.py script in the reference_results directory.
        """
        model = _DummyModel()

        # Check that we built a function that looks like a redback function (with time first and
        # then the model parameters).
        func = make_learned_model_callable(model)
        assert isinstance(func, types.FunctionType)
        assert inspect.getfullargspec(func).args == ["time", "freq", "amp", "center", "width"]

        # Check that we can evaluate the function.
        spectra1 = func(
            time=model.times,
            freq=1.0,
            amp=1e10,
            center=3100.0,  # Peak at 3100 Angstroms
            width=1000.0,  # 1000 Angstrom stddev
            redshift=0.5,
            output_format="flux_density",
            frequency=3000.0,
        )
        assert spectra1.shape == (len(model.times),)

        # Check that we can evaluate the function for spectra output. There should
        # be three components: time, lambdas, and spectra
        spectra2 = func(
            time=model.times,
            freq=1.0,
            amp=1e10,
            center=3100.0,  # Peak at 3100 Angstroms
            width=1000.0,  # 1000 Angstrom stddev
            redshift=0.5,
            output_format="spectra",
        )
        assert len(spectra2) == 3
        assert spectra2.spectra.shape == (len(spectra2.time), len(spectra2.lambdas))
